#!/bin/bash

PROGNAME=${0##*/}

function fatal() { echo "FATAL: $PROGNAME: $*" >&2; exit 2; }

if [[ -L $0 && $PROGNAME == *-run ]]; then
    default_ct_name=${PROGNAME%-run}
else
    default_ct_name=kompot
fi

CONTAINER_NAME=${CONTAINER_NAME:-$default_ct_name}
CONTAINER_IMAGE=${CONTAINER_IMAGE:-zenetys/kompot}
# set empty to prevent --rm
CONTAINER_RM=${CONTAINER_RM-1}
CONTAINER_DETACH=${CONTAINER_DETACH-}
CONTAINER_NETWORK=${CONTAINER_NETWORK-}
CONTAINER_IP=${CONTAINER_IP-}
# --restart on|on-failure[:max-retries]|always|unless-stopped
CONTAINER_RESTART=${CONTAINER_RESTART-}
CONTAINER_STOP_TIMEOUT=${CONTAINER_STOP_TIMEOUT-30}
VOLUME_ETC_KOMPOT=${VOLUME_ETC_KOMPOT-~/"app/$CONTAINER_NAME/etc"}
VOLUME_VAR_LIB_KOMPOT=${VOLUME_VAR_LIB_KOMPOT-~/"app/$CONTAINER_NAME/data"}
VOLUME_VAR_LOG=${VOLUME_VAR_LOG-~/"app/$CONTAINER_NAME/log"}
PUBLISH_HTTPD_PORT=${PUBLISH_HTTPD_PORT-0.0.0.0:8083}
PUBLISH_HTTPD_TLS_PORT=${PUBLISH_HTTPD_TLS_PORT-}
PUBLISH_SSHD_PORT=${PUBLISH_SSHD_PORT-0.0.0.0:2222}
PUBLISH_RSYSLOG_UDP_PORT=${PUBLISH_RSYSLOG_UDP_PORT-0.0.0.0:5514}
PUBLISH_RSYSLOG_TCP_PORT=${PUBLISH_RSYSLOG_TCP_PORT-0.0.0.0:5514}
PUBLISH_SNMPTRAPD_PORT=${PUBLISH_SNMPTRAPD_PORT-0.0.0.0:1162}

DOCKER_RUN_OPTS=()

config=$CONFIG
[[ -z $config ]] && config=(
    ~/.config/"$PROGNAME.$CONTAINER_NAME"
    ~/.config/"$PROGNAME"
)
for c in "${config[@]}"; do
    [[ -r $c ]] && { source "$c"; break; }
done

while (( $# > 0 )); do
    case "$1" in
        --) shift; break ;;
        *) DOCKER_RUN_OPTS+=( "$1" ) ;;
    esac
    shift
done

docker ps -a --format '{{.Names}}' |grep -qFx "$CONTAINER_NAME"
(( $? == 0 )) && fatal "Container $CONTAINER_NAME already exists"

exec docker run \
    ${CONTAINER_RM:+--rm} \
    ${CONTAINER_DETACH:+--detach} \
    ${CONTAINER_NETWORK:+--network "$CONTAINER_NETWORK"} \
    ${CONTAINER_IP:+--ip "$CONTAINER_IP"} \
    ${CONTAINER_RESTART:+--restart "$CONTAINER_RESTART"} \
    ${CONTAINER_STOP_TIMEOUT:+--stop-timeout "$CONTAINER_STOP_TIMEOUT"} \
    --name "$CONTAINER_NAME" \
    --hostname "$CONTAINER_NAME" \
    --tmpfs /run \
    --tmpfs /tmp \
    ${VOLUME_ETC_KOMPOT:+--volume "$VOLUME_ETC_KOMPOT:/etc/kompot"} \
    ${VOLUME_VAR_LIB_KOMPOT:+--volume "$VOLUME_VAR_LIB_KOMPOT:/var/lib/kompot"} \
    ${VOLUME_VAR_LOG:+--volume "$VOLUME_VAR_LOG:/var/log"} \
    ${PUBLISH_HTTPD_PORT:+--publish "$PUBLISH_HTTPD_PORT:80/tcp"} \
    ${PUBLISH_HTTPD_TLS_PORT:+--publish "$PUBLISH_HTTPD_TLS_PORT:443/tcp"} \
    ${PUBLISH_SSHD_PORT:+--publish "$PUBLISH_SSHD_PORT:22/tcp"} \
    ${PUBLISH_RSYSLOG_UDP_PORT:+--publish "$PUBLISH_RSYSLOG_UDP_PORT:514/udp"} \
    ${PUBLISH_RSYSLOG_TCP_PORT:+--publish "$PUBLISH_RSYSLOG_TCP_PORT:514/tcp"} \
    ${PUBLISH_SNMPTRAPD_PORT:+--publish "$PUBLISH_SNMPTRAPD_PORT:162/udp"} \
    "${DOCKER_RUN_OPTS[@]}" \
    "$CONTAINER_IMAGE" \
    "$@"
