#!/bin/bash
cd /
exec 0>&- 0</dev/null
exec 1>&- 1>/dev/null
exec 2>&- 2>/dev/null
OPTIONS="-Lsd"
[[ -r /etc/sysconfig/snmptrapd ]] && source /etc/sysconfig/snmptrapd
exec /usr/sbin/snmptrapd $OPTIONS -f
