#!/bin/bash
svdir=$(readlink -f "${0%/*}")
svname=${svdir##*/}

# If service terminates with an unclean exit code (ie: != 0), but not
# abnormally (ie != -1), call the perl script with --help and if that
# fails, cancel infinite restart of the service, assuming some perl
# modules are missing.
if (( $1 > 0 )) && ! /opt/centreon-vmware/bin/centreon_vmware.pl --help >/dev/null 2>&1; then
    logger -t "$svname" -p err "Service $svname exited status $1, some perl modules may be missing, disabling restart"
    sv down "$svdir"
fi
